[package]
name = "zinnebeeld"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "6"
euclid = "0.22"
glium = "0.35"
image = { version = "0.25", features = ["png"] }
softbuffer = "0.4"
thiserror = "1"

[profile.release]
debug = true
